### ISSUE TITLE
Add Lua implementation for Observer pattern

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#13]

**Comment by monika-789** [comment]
Hi @ash-teach, I would like to work on this issue. Thank you!

**Comment by jaskaransingh9990** [comment]
Hi @ash-teach can you assign this work to me. thank you

**Comment by manasvi111** [comment]
Hii @ash-teach, Can I work on this issue?

**Comment by Dhuds1** [comment]
@jaskaransingh9990 @manasvi111 hey! @monika-789 is currently assigned to this issue, however, you can help if
 @monika-789 they would like it!

**Comment by ting-dev-coder** [comment]
closed this as completed in #74
