### ISSUE TITLE
Add implementation / description of model view controller (MVC)

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#14]

**Comment by ash-teach** [comment]
The specific language and framework tbd. I think React is MVC? Maybe with some JavaScript libraries?

**Comment by YogeshManni** [comment]
Hi Ashley, I would like to work on this issue. I will be using React, Node.js and Mongoose to describe the MVC architecture.

**Comment by ash-teach** [comment]
Closed by PR #51.
