### ISSUE TITLE
Add implementation / description of model view viewmodel (MVVM)

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#15]

**Comment by ash-teach** [comment]
Perhaps easiest to _implement_ in Kotlin, but may require a lot of boilerplate code with a sample app. Perhaps DGL 114 students can collaborate on this one?

**Comment by ting-dev-coder** [comment]
I believe it can be implemented solely in JavaScript. MVVM is implemented in Vue3 using Proxy/Reflect, and I will refer to their source code as a guide.
I will assign this to myself

**Comment by ash-teach** [comment]
Closed by #58
