### ISSUE TITLE
Final README.md editing pass for formatting consistency

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#21]
Ensure that all formatting is consistent throughout the document. Also reference progress in #22. The following checklist compiles some of the more common issues:

- [ ] Ensure headings are logically ordered (i.e. don't skip heading levels: `#` is followed by `##` is followed by `###` etc.)
- [ ] All code blocks are wrapped in triple backticks (i.e. \```)
- [ ] All code blocks use appropriate language annotations for syntax highlighting (i.e. \```javascript)
- [ ] All code in code blocks is properly indented and white space is used appropriately
- [ ] All in-line references to code (i.e. keywords, variable names, short statements or expressions, etc.) are wrapped in single backticks (i.e. \`)
- [ ] Markdown formatting is used appropriately and consistently (i.e. ordered and unordered lists, tables, bolding and italics).
- [ ] Whitespace is correctly used in the raw `.md` code (i.e. a new line between every paragraph (including separating headers from text and lists from text).
- [ ] All spurious HTML tags are removed (i.e. no `<br>` or similar tags are included)
- [ ] All markdown images include an appropriate alt-text.
- [ ] All links are appropriately formatted as hyperlinks

**Comment by kattsky** [comment]
Good morning @ash-teach, kindly assign this task to me. Thank you.

**Comment by ash-teach** [comment]
Done. To be clear though, this task shouldn't be worked on until after most of the rest of the work is done - i.e. during the last week before submission. Likely you will also want to enlist the help of others - so feel free to add the "help wanted" label.

**Comment by Hpunia1** [comment]
Hello @ash-teach can I contribute in this task with @kattsky as it required team work to fulfill this task. Could you please assign me this task.

**Comment by ATodd1** [comment]
Hi @ash-teach I would like to help with this as well if I still can

**Comment by kattsky** [comment]
Hi @Hpunia1 and @ATodd1, thank you for being here :-)

Here's a quick update:
I've raised a PR for the 2 README files I've proofed and edited. Please refer to [Final README edit](https://github.com/nic-dgl104-winter-2024/pattern-library/pull/95)

I've left the following README files available for your review:
- Creational/Dart/README
- Creational/Javascript/README
- Creational/ReactNative/README
- MVC/README
- observers/README

**Comment by sabrina01031997** [comment]
Hi @ash-teach I would like to help with this as well.

**Comment by Hpunia1** [comment]
https://github.com/nic-dgl104-winter-2024/pattern-library/pull/100 
hey @ash-teach @sabrina01031997 @ATodd1 
So I edited and fixed the issues for

Creational/Dart/README
Creational/Javascript/README
MVC/README

**Comment by ting-dev-coder** [comment]
closed this as merged in  #95 , #100 and #97
