### ISSUE TITLE
Write definition of Observer pattern in README.md

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#23]
- [ ] Identify one or more appropriate references.
- [ ] Write one or two paragraphs describing the **purpose** of Observer pattern (no code necessary).
- [ ] Include well-formatted references (either immediately following the description, or in a references section).

**Comment by Jessica-Pelletier** [comment]
Hi @ash-teach , I can take this one! Please assign to me :)

**Comment by mijuanmontalvo** [comment]
Hello @ash-teach, I would like to work in this issue, could you assign me it?
I am new in design pattern, and I would like to start with the definitions.

**Comment by ash-teach** [comment]
Hi @mijuanmontalvo - @Jessica-Pelletier has already been assigned to this issue. Can you communicate with @Jessica-Pelletier to see if she would like support/help? You can do so here, or via Slack. Or I can pass around @northislandcollege email addresses, if you prefer.

**Comment by Jessica-Pelletier** [comment]
@ash-teach The issue is complete and the pull request is awaiting review! However, if theres's anything you think you can add to it! By all means, please do! @mijuanmontalvo

**Comment by ash-teach** [comment]
Closed by PR #37
