### ISSUE TITLE
Write definition of MVC pattern in README.md

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#24]
- [ ] Identify one or more appropriate references.
- [ ] Write one or two or three paragraphs describing the **purpose** of the MVC architectural pattern (no code necessary).
- [ ] Include well-formatted references (either immediately following the description, or in a references section).

**Comment by michiwo1** [comment]
@ash-teach 
Hi Ashley,
Could you assign this issue to me?
And Am I supposed to make a pull request regarding the contents of this issue?

**Comment by ash-teach** [comment]
Yes @michiwo1! Please fork this repository and make changes in a local branch (specific changes requested are listed in the checklist in the issue description), then open a pull request back to the original repository. 

If any of the process is unclear, please watch the Community Code video walkthrough guides in the Brightspace Week 10 content.

**Comment by michiwo1** [comment]
Hi @ash-teach,
I think this issue should be closed.
https://github.com/nic-dgl104-winter-2024/pattern-library/pull/41#issuecomment-2016095562

**Comment by oakintunde** [comment]
Hello @ash-teach Please I am working on this too as my part 2.

**Comment by ting-dev-coder** [comment]
closed this as merged in #41
