### ISSUE TITLE
Write definition of MVVM pattern in README.md

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#25]
- [ ] Identify one or more appropriate references.
- [ ] Write one or two paragraphs describing the **purpose** of MVVM architectural pattern (no code necessary).
- [ ] Include well-formatted references (either immediately following the description, or in a references section).

**Comment by lcgraves** [comment]
Hi @ash-teach, can I be assigned to this please?

**Comment by ash-teach** [comment]
Closed by #52
