### ISSUE TITLE
Add JavaScript implementation for Observer pattern

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#3]

**Comment by kattsky** [comment]
Hi @ash-teach, I'd like to work with Swathy  on this issue please. Thank you

**Comment by john24alex** [comment]
Hi @ash-teach, I could work on this issue mainly. 
Regards

**Comment by ash-teach** [comment]
Hi @john24alex - since we have two people working on this already, I'd like you to communicate with them to see if they ned support first. You can ask here, or on Slack, or via email.

**Comment by john24alex** [comment]
@kattsky  and @ashandoak any comments, about me working on this issue too?
Regards

**Comment by monika-789** [comment]
Hi @ash-teach, I would like to work on this issue. Thank you!

**Comment by swathysukumaran** [comment]
Hi.. Katrina and I are working on the issue. Currently, we don't need support for coding. If we get stuck at some point or for code review, we will need help.

**Comment by ash-teach** [comment]
Thanks @swathysukumaran. In that case, both @john24alex and @monika-789: you are welcome to provide code review when the pull request for the implementation is provided.

**Comment by ash-teach** [comment]
Closed by #49
