### ISSUE TITLE
Add Java implementation for Singleton pattern 

### ISSUE THREAD

**Issue by ting-dev-coder** [nic-dgl104-winter-2024/pattern-library#34]

**Comment by Abdulrahman295** [comment]
Hello. Can I work on this issue?

**Comment by ash-teach** [comment]
Done! Don't forget to sync your fork up to the current version of the base repository before starting your work, and check out the existing work to get a sense on how to proceed. Feel free to comment on this thread if you have questions or need any support.

**Comment by ash-teach** [comment]
Closed by PR #36.
