### ISSUE TITLE
Add Java implementation for Observer pattern

### ISSUE THREAD

**Issue by ting-dev-coder** [nic-dgl104-winter-2024/pattern-library#35]

**Comment by Aawofeso** [comment]
Hello @ashandoak , Can i be assigned to this?

**Comment by Aawofeso** [comment]
Hello @ ash-teach, Can I be assigned to this?

**Comment by AditiVatish** [comment]
Hello @ash-teach , Can i be assigned to this?

**Comment by Bhoomi3637** [comment]
Hello @ash-teach ,i would like to work on this issue ,can i be assigned to this?

**Comment by ash-teach** [comment]
I have assigned @AditiVatish and @Bhoomi3637. @Aawofeso if you want to help out just say so and we can add you back to this issue.

**Comment by Aawofeso** [comment]
I would like to be added to the issue.
________________________________

**Comment by ash-teach** [comment]
In that case, the three of you will work together on this: Please collaborate via this comment thread, or Slack (or whatever method is easiest).

**Comment by kuljit95** [comment]
@ash-teach , I would like to choose this issue. Can I take this ?

**Comment by ash-teach** [comment]
We already have three on this one @kuljit95, and you have some other issues assigned to you as well, so I won't assign you to this one. However, please do subscribe to the issue and keep watch as when a PR comes through you are welcome to perform a code review - which is a valuable contribution.

**Comment by ting-dev-coder** [comment]
closed this as completed in #80 and #81
