### ISSUE TITLE
Add C# implementation of Singleton pattern

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#46]

**Comment by manasvi111** [comment]
Hi Ashley, I would like to work on this issue if you can assign me this that will be much appreciated!

Thank you in advance!

**Comment by manasvi111** [comment]
@ash-teach , Is there any update on this?

**Comment by mrsaif888** [comment]
Hey Ashley can i work on this issue?

**Comment by ash-teach** [comment]
Hi @manasvi111 and @mrsaif888 - If you're interested in working on this, you should discuss with those who are already assigned to see if they need support. I don't think more than three people on a single coding issue is appropriate, unless there is a clear and easy division of labour.

**Comment by ting-dev-coder** [comment]
closed this as completed in #72
