### ISSUE TITLE
Add C# implementation of Observer pattern

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#47]

**Comment by alinaghale88** [comment]
Hi @ash-teach can you assign this to me as well?

**Comment by kuljit95** [comment]
Hii @ash-teach , I would like to work on this issue. Please assign me this ?

**Comment by ash-teach** [comment]
@alinaghale88: @kuljit95 is interested in helping - would you like some support on this issue?

**Comment by alinaghale88** [comment]
@ash-teach I am okay with @kuljit95 joining me in this project

**Comment by jaskaransingh9990** [comment]
hi @kuljit95  @alinaghale88 i want to work with you on this repo is it ok for you.

**Comment by sabrina01031997** [comment]
Hii @ash-teach , I would like to work on this issue. Can you please assign me this?

**Comment by alinaghale88** [comment]
@jaskaransingh9990 I and @kuljit95 have worked on our topics of interest for this issue. If you want to contribute then you can either do a code review for us or ask @ash-teach

**Comment by sabrina01031997** [comment]
Hi @ash-teach , I would like to work on this issue. Can you please assign me this?

**Comment by sabrina01031997** [comment]
Hello, @kuljit95 @alinaghale88 i want to work with you on your repo is it ok for you???? Do you need any help???

**Comment by ting-dev-coder** [comment]
closed this as completed in #91
