### ISSUE TITLE
Add Javascript implementation of Template pattern

### ISSUE THREAD

**Issue by ting-dev-coder** [nic-dgl104-winter-2024/pattern-library#57]

**Comment by ting-dev-coder** [comment]
I opened the issue because this is one of the patterns that I find really useful when communicating with machines (IOT). Since it's a pattern I've used before, I'd like to go over it again, and I will assigned this to myself.

**Comment by nazrinzuwair** [comment]
Hello @ ash-teach, Can I be assigned to this?

**Comment by manasvi111** [comment]
Hello, @ash-teach , Can you please assign me this one?

**Comment by manasvi111** [comment]
Hello @nazrinzuwair , Is it okay with you if he assigned us together?

**Comment by nazrinzuwair** [comment]
Hi @manasvi111 
Yes we can work together

**Comment by mrsaif888** [comment]
@ash-teach can i work on this one?

**Comment by mrsaif888** [comment]
@nazrinzuwair @manasvi111   i also want to work on this one can you please add to this contribution

**Comment by ting-dev-coder** [comment]
@nazrinzuwair @manasvi111 @mrsaif888 
Hi guys, glad to know many are interested in this pattern. 
However, I am currently working on this issue and don't need code support at the moment. If you would like to contribute to this pattern for different languages or even other patterns, after consulting with 
@ash-teach , you could open issues for them.

**Comment by ash-teach** [comment]
Thanks, @ting-dev-coder. @nazrinzuwair, @manasvi111, @mrsaif888 you are welcome to continue to watch this issue and when @ting-dev-coder opens a PR you can do code review. 

Issue #26 requests that you take some time to research alternative design patterns and propose some for addition. If you'd like to work on that issue you're welcome to add some ideas and commentary to the thread. If you come up with a good proposal then we can add it in (as was done with abstract factory in #50, and this issue that @ting-dev-coder added).

**Comment by ting-dev-coder** [comment]
closed this as completed in #88
