### ISSUE TITLE
Add Kotlin implementation for Template pattern 

### ISSUE THREAD

**Issue by ting-dev-coder** [nic-dgl104-winter-2024/pattern-library#65]

**Comment by abhiram-shaji** [comment]
@ash-teach @ting-dev-coder I would love to work on this, my idea is to create a template method pattern with a similar structure as that of the existing singleton pattern.

1. I plan to create an abstract class, NameProcessor, with a template method and steps that will be implemented in the subclass.
2. Then a subclass which will consist of the implementation of those steps in the abstract class.
3. Finally, a main method to demonstrate the template pattern.

**Comment by ting-dev-coder** [comment]
closed this as completed in #89
