### ISSUE TITLE
Add Javascript implementation of Strategy pattern

### ISSUE THREAD

**Issue by ting-dev-coder** [nic-dgl104-winter-2024/pattern-library#67]

**Comment by manasvi111** [comment]
Hello @ash-teach, either this or the PHP one(#68) will be best match for, Please assign me one of this! 

Thank you!!

**Comment by 8968sam** [comment]
Hii @ash-teach, can i work on this ?

**Comment by ting-dev-coder** [comment]
closed this as completed in #86
