### ISSUE TITLE
Add PHP implementation of Strategy pattern 

### ISSUE THREAD

**Issue by ting-dev-coder** [nic-dgl104-winter-2024/pattern-library#68]

**Comment by Dhuds1** [comment]
Not claiming it, but if no one wants this by `Wednesday March 27th` I'd like to work on this!

**Comment by manasvi111** [comment]
Hello @ash-teach, I would like to work in this issue, Please assign me this.

**Comment by Dhuds1** [comment]
@manasvi111 I've assigned you

**Comment by 8968sam** [comment]
Hiii @ash-teach, @Dhuds1 can i work on this one as I saw @manasvi111 is already working on issuse #67

**Comment by oakintunde** [comment]
If this is still open, please I am working on this too @ash-teach

**Comment by ting-dev-coder** [comment]
closed this as merged in https://github.com/nic-dgl104-winter-2024/pattern-library/pull/104

**Comment by ting-dev-coder** [comment]
closed this as merged in https://github.com/nic-dgl104-winter-2024/pattern-library/pull/104
