### ISSUE TITLE
Write definition of Strategy pattern in README.md

### ISSUE THREAD

**Issue by ting-dev-coder** [nic-dgl104-winter-2024/pattern-library#69]

**Comment by jaskaransingh9990** [comment]
hi @ash-teach can you assign me this work

**Comment by virenbhadiyadra** [comment]
hi @ash-teach can you please assign this task to me?

**Comment by jaskaransingh9990** [comment]
hey @Dhuds1 i am unable to find this issue in backlog section. i want to move it to review section.

**Comment by tharinduj31** [comment]
Hi @ash-teach  can you please assign this task to me(@tharinduj31) ?

**Comment by jaskaransingh9990** [comment]
hey @ash-teach  i am unable to find this issue in backlog section. i want to move it to review section.

**Comment by ting-dev-coder** [comment]
closed this as merged in #84
