### ISSUE TITLE
Add React Native implementation for Singleton pattern

### ISSUE THREAD

**Issue by ash-teach** [nic-dgl104-winter-2024/pattern-library#8]

**Comment by Anjitha-94** [comment]
Hai, can I get this issue for solving part 2?

**Comment by ash-teach** [comment]
Done. You have been assigned. Though, to be honest, I'm not sure how easy Singleton is in React Native (I'm not that familiar with the framework myself). 

If you have questions, or if you need some help, please feel free to post comments here. If it starts looking like it's not going to be feasible, we can always redirect elsewhere.

**Comment by Anjitha-94** [comment]
How can I get the readme file for this issue as i need to find more about the project?

**Comment by ash-teach** [comment]
@Anjitha-94 if you visit the [pattern/singleton](https://github.com/nic-dgl104-winter-2024/pattern-library/tree/main/patterns/singleton) folder in the repository you can see the Singleton-specific README.md file, which describes the pattern. You can also visit the week 9 content on Brightspace to learn more about Singleton pattern, if you are unfamiliar.

**Comment by BasranS** [comment]
Hi @ash-teach, I would like to work on this task. Please assign it to me!

**Comment by BALJITSINGH23** [comment]
Hi @ash-teach , can you assign this task to me for my part 2 of code community.

**Comment by BasranS** [comment]
Hi @ash-teach, I can work together on this issue with @BALJITSINGH23 and @Anjitha-94.

**Comment by ash-teach** [comment]
@Anjitha-94 - would you like to have help from @BALJITSINGH23 and @BasranS? If so, please acknowledge here and I can assign all three to this task. **Remember**, however, that you will all have to demonstrate individual work that you have done to complete this task!

**Comment by Anjitha-94** [comment]
Okay no issues ,  hopefully we all together can solve this issue

**Comment by ash-teach** [comment]
@BasranS and I spoke earlier today about splitting the work up for this issue. Please get in touch (on this comment thread, or Slack or email) to discuss with me if you need support in identifying a way forward.

**Comment by Anjitha-94** [comment]
We all meet today in our capstone class and decided to do code separately as their own work

**Comment by BALJITSINGH23** [comment]
hi @ash-teach  i add some code using function with exciting code. can you give me feedback on that

**Comment by ting-dev-coder** [comment]
closed this as merged in #102 and #78
